jobs:
  test-secrets1:
    runs-on: windows-latest
    env:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

    steps:
      - name: Test if AZURE_PUBLISH_PROFILE and DB_CONNECTION_STRING secrets exist
        run: |
          if (-not $env:AZURE_PUBLISH_PROFILE) {
            Write-Output "❌ AZURE_PUBLISH_PROFILE secret not set"
            exit 1
          } else {
            Write-Output "✅ AZURE_PUBLISH_PROFILE secret is available"
          }

          if (-not $env:DB_CONNECTION_STRING) {
            Write-Output "❌ DB_CONNECTION_STRING secret not set"
            exit 1
          } else {
            Write-Output "✅ DB_CONNECTION_STRING secret is available"
          }
