name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest # or windows-latest — doesn’t matter here

    steps:
      - name: Test if secret exists
        run: |
          if [ -z "${{ secrets.AZURE_PUBLISH_PROFILE }}" ]; then
            echo "❌ Secret not set"
            exit 1
          else
            echo "✅ Secret is available"
          fi
