name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets1:
    runs-on: windows-latest # or windows-latest — doesn’t matter here

    steps:
      - name: Test if secret exists
        run: |
          if [ -z "${{ secrets.AZURE_PUBLISH_PROFILE }}" ]; then
            echo "❌ Secret not set"
            exit 1
          else
            echo "✅ Secret is available"
          fi
jobs:
  test-secrets2:
    steps:
      - name: Test if secret exists
        run: |
          if [ -z "${{ secrets.DB_CONNECTION_STRING }}" ]; then
            echo "❌ Secret not set"
            exit 1
          else
            echo "✅ Secret is available"
          fi